# Generated by Django 2.2.5 on 2020-01-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_article_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Racer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('victoryRatio', models.CharField(max_length=10)),
                ('secondRatio', models.CharField(max_length=10)),
                ('thirdRatio', models.CharField(max_length=10)),
                ('raceNum', models.CharField(max_length=10)),
                ('finalJoinedNum', models.CharField(max_length=10)),
                ('victoryNum', models.CharField(max_length=10)),
                ('startAvg', models.CharField(max_length=10)),
                ('flyingNum', models.CharField(max_length=10)),
                ('lateNum', models.CharField(max_length=10)),
                ('Ability', models.CharField(max_length=10)),
                ('firstNum', models.CharField(max_length=10)),
                ('secondNum', models.CharField(max_length=10)),
                ('thirdNum', models.CharField(max_length=10)),
                ('fourthNum', models.CharField(max_length=10)),
                ('fivthNum', models.CharField(max_length=10)),
                ('sixthNum', models.CharField(max_length=10)),
            ],
        ),
    ]
