# Generated by Django 3.1 on 2021-01-25 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bbs', '0009_auto_20200816_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='店名')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='end',
            field=models.DateTimeField(null=True, verbose_name='終了時間'),
        ),
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='予約者名'),
        ),
        migrations.AddField(
            model_name='book',
            name='start',
            field=models.DateTimeField(null=True, verbose_name='開始時間'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='表示名')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.store', verbose_name='店舗')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ログインユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='開始時間')),
                ('end', models.DateTimeField(verbose_name='終了時間')),
                ('name', models.CharField(max_length=255, verbose_name='予約者名')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.staff', verbose_name='スタッフ')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bbs.staff', verbose_name='スタッフ'),
        ),
        migrations.AddConstraint(
            model_name='staff',
            constraint=models.UniqueConstraint(fields=('user', 'store'), name='unique_staff'),
        ),
    ]
