# Generated by Django 3.1 on 2021-01-25 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0010_auto_20210125_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='staff',
        ),
    ]
