# Generated by Django 3.1.5 on 2021-01-29 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0012_auto_20210128_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bbs.book'),
        ),
    ]
